// This file is generated by Astro DB
declare module 'astro:db' {
	export const Tourdate: import("@astrojs/db/runtime").Table<
		"Tourdate",
		{"date":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"date","collection":"Tourdate"}},"venue":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"venue","collection":"Tourdate","primaryKey":false,"optional":false}},"city":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"city","collection":"Tourdate","primaryKey":false,"optional":false}},"country":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"country","collection":"Tourdate","primaryKey":false,"optional":false}},"url":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"url","collection":"Tourdate","primaryKey":false,"optional":false}},"other":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"other","collection":"Tourdate","primaryKey":false,"optional":false}}}
	>;
	export const Release: import("@astrojs/db/runtime").Table<
		"Release",
		{"date":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"date","collection":"Release"}},"title":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"title","collection":"Release","primaryKey":false,"optional":false}},"cat":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"cat","collection":"Release","primaryKey":false,"optional":false}},"hasImage":{"type":"boolean","schema":{"optional":true,"unique":false,"deprecated":false,"name":"hasImage","collection":"Release"}},"format":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"format","collection":"Release","primaryKey":false,"optional":false}},"label":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"label","collection":"Release","primaryKey":false,"optional":false}},"tracklisting":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"tracklisting","collection":"Release","primaryKey":false,"optional":true}},"notes":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"notes","collection":"Release","primaryKey":false,"optional":true}}}
	>;
}
