// This file is generated by Astro DB
declare module 'astro:db' {
	export const Tourdate: import("@astrojs/db/runtime").Table<
		"Tourdate",
		{"date":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"date","collection":"Tourdate"}},"venue":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"venue","collection":"Tourdate","primaryKey":false,"optional":false}},"city":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"city","collection":"Tourdate","primaryKey":false,"optional":false}},"country":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"country","collection":"Tourdate","primaryKey":false,"optional":false}},"url":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"url","collection":"Tourdate","primaryKey":false,"optional":false}},"other":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"other","collection":"Tourdate","primaryKey":false,"optional":false}}}
	>;
}
